export const routeConfig = {
  All: 'all',
  '1': 'radial',
  '2': 'radial',
  '3': 'radial',
  '4': 'radial',
  '5': 'radial',
  '6': 'radial',
  '7': 'radial',
  '8': 'radial',
  '9': 'radial',
  '10': 'radial',
  '11': 'radial',
  '12': 'radial',
  MM: 'transverse',
  SZ: 'transverse',
  CK: 'transverse',
  PP: 'transverse',
  A: 'loop',
  B: 'loop',
  C: 'loop'
};
